# Generated by Django 3.1.7 on 2021-04-02 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('club_type', models.CharField(default='none', max_length=200)),
                ('club_budget', models.IntegerField(default=0)),
                ('contactEmail', models.EmailField(default='nullnull@null.ca', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('schoolID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=200)),
                ('location', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(default=0, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=200)),
                ('Year_of_study', models.IntegerField(default=0)),
                ('major', models.CharField(default='none', max_length=200)),
                ('phoneNumber', models.CharField(default='none', max_length=200)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.university')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomNo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('buildingName', models.CharField(default='none', max_length=200)),
                ('Capacity', models.IntegerField(default=0)),
                ('location', models.CharField(default='none', max_length=200)),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.university')),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.room')),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date')),
                ('event_type', models.CharField(default='none', max_length=200)),
                ('description', models.CharField(default='none', max_length=200)),
                ('RoomNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.room')),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tresurer', models.BooleanField()),
                ('VicePresident', models.BooleanField()),
                ('President', models.BooleanField()),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('studnetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.CharField(default='none', max_length=200)),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('studnetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.student')),
            ],
        ),
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date')),
                ('message', models.CharField(default='none', max_length=200)),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
