# Generated by Django 3.1.7 on 2021-04-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='schoolID',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='clubs.university'),
        ),
    ]
