# Generated by Django 3.1.7 on 2021-03-25 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='votes',
        ),
        migrations.AddField(
            model_name='club',
            name='club_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='contactEmail',
            field=models.EmailField(default='null@null.ca', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
