# Generated by Django 3.1.7 on 2021-03-25 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210325_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Event date')),
                ('message', models.CharField(default='none', max_length=200)),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
